import { SITE } from "@/lib/site-config";
import { SITE_URL } from "@/lib/seo";

export const PRIVACY_LAST_UPDATED = "5th November 2025";

const DOMAIN = SITE_URL.replace(/^https?:\/\//, "");
const CONTACT_URL = `${SITE_URL}/contact`;

export type PrivacyBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] };

export function getPrivacyPolicyBlocks(): PrivacyBlock[] {
  const company = SITE.legalName;

  return [
    { type: "p", text: `Our Privacy Policy was last updated on ${PRIVACY_LAST_UPDATED}` },
    {
      type: "p",
      text: `This Privacy Policy describes and explains the Policy of ${company} (hereinafter referred to as "Company") pertaining to the procedures of collection, use and disclosure of any information so collected about the Buyers, Vendors, Distributors, Employees and any other Business Associate while using the services of the Company, and how the Privacy Policy of the Company protects Your privacy rights as per the prevailing Indian Legal System.`,
    },
    { type: "h2", text: "Interpretation and Definitions" },
    { type: "h3", text: "Interpretation" },
    {
      type: "p",
      text: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
    },
    { type: "h3", text: "Definitions" },
    { type: "p", text: "For the purposes of this Privacy Policy:" },
    {
      type: "ul",
      items: [
        '"Account" means a unique account created for You to access our Service or parts of our Service.',
        '"Business" for the purpose of Privacy Policy refers to the Company as the legal entity that collects information about its clients who are doing or intend to do business with the Company and determines the purposes and means of the processing of such information.',
        '"Country" refers to India.',
        '"You" refers to Client individually or organization.',
        `"Us" refers to Company "${company}".`,
        `We / "Our(s)" refers to Company "${company}" including the authorized official.`,
        "Personal Data refers to the officially designated personal information about the individual visiting the Company website.",
        '"Cookies" are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
        '"Data Controller", for the purposes of the GDPR (General Data Protection Regulation), refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of the business data collected about its Clients.',
        '"Device" means any device that can access the Service such as a computer, a cell phone or a digital tablet.',
        '"Personal Data" is any information that relates to an identified or identifiable individual.',
        '"Business Data" refers to data pertaining to the business activity or any activity allied or collateral to such business activity; it includes the individual carrying on such activities.',
        '"Service" refers to the Website.',
        '"Service Provider" means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. For the purpose of the GDPR, Service Providers are considered Data Processors.',
        '"Usage Data" refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
        `"Website" refers to ${company}, accessible from ${DOMAIN}.`,
        '"You" means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
      ],
    },
    { type: "h2", text: "Collecting and Using Your Personal & Business Data" },
    { type: "h3", text: "Types of Data Collected" },
    { type: "h3", text: "Personal Data" },
    {
      type: "p",
      text: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
    },
    {
      type: "ul",
      items: [
        "Email address",
        "First name and last name",
        "Phone number",
        "Address, State, Province, ZIP/Postal code, City",
        "Usage Data",
      ],
    },
    { type: "h3", text: "Usage Data" },
    {
      type: "p",
      text: "Usage Data is collected automatically when using the Service via Mobile, Browser or our Website.",
    },
    {
      type: "p",
      text: "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
    },
    { type: "h3", text: "Tracking Technologies and Cookies" },
    {
      type: "p",
      text: "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.",
    },
    { type: "h2", text: "Use of Your Personal Data" },
    {
      type: "p",
      text: "The Company may use Personal Data for the following purposes:",
    },
    {
      type: "ul",
      items: [
        "To provide and maintain our Service, including to monitor the usage of our Service.",
        "To manage Your Account: To manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
        "For the performance of a contract: The development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
        "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
        "To provide You with news, special offers and general information about other goods, services and events which We offer that are similar to those that You have already purchased or enquired about unless You have opted not to receive such information.",
        "To manage Your requests: To attend and manage Your requests to Us.",
        "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
        "For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and Your experience.",
      ],
    },
    {
      type: "p",
      text: "We may share Your personal information in the following situations:",
    },
    {
      type: "ul",
      items: [
        "With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.",
        "For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
        "With Affiliates: We may share Your information with our affiliates, in which case We will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.",
        "With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.",
        "With other users: When You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
        "With Your consent: We may disclose Your personal information for any other purpose with Your consent.",
      ],
    },
    { type: "h2", text: "Retention of Your Personal & Business Data" },
    {
      type: "p",
      text: "The Company will retain Your Personal & Business Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
    },
    {
      type: "p",
      text: "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
    },
    { type: "h2", text: "Transfer of Your Data" },
    {
      type: "p",
      text: "Your information, including Personal Data & Business Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
    },
    {
      type: "p",
      text: "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
    },
    {
      type: "p",
      text: "The Company will take all steps reasonably necessary to ensure that Your Personal & Business data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal & Business Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
    },
    { type: "h2", text: "Disclosure of Your Personal & Business Data" },
    { type: "h3", text: "Business Transactions" },
    {
      type: "p",
      text: "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
    },
    { type: "h3", text: "Law enforcement" },
    {
      type: "p",
      text: "Under certain circumstances, the Company may be required to disclose Your Personal & Business Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
    },
    { type: "h3", text: "Other legal requirements" },
    {
      type: "p",
      text: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
    },
    {
      type: "ul",
      items: [
        "Comply with a legal obligation",
        "Protect and defend the rights or property of the Company",
        "Prevent or investigate possible wrongdoing in connection with the Service",
        "Protect the personal safety of Users of the Service or the public",
        "Protect against legal liability",
      ],
    },
    { type: "h2", text: "Security of Your Personal & Business Data" },
    {
      type: "p",
      text: "The security of Your Personal & Business Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, we cannot guarantee its absolute security.",
    },
    { type: "h2", text: "Detailed Information on the Processing of Your Personal Data" },
    {
      type: "p",
      text: "The Service Providers may have access to Your Personal & Business Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.",
    },
    { type: "h3", text: "Analytics" },
    {
      type: "p",
      text: "We may use third-party Service providers to monitor and analyze the use of our Service.",
    },
    { type: "h3", text: "Email Marketing" },
    {
      type: "p",
      text: "We may use Your Personal & Business Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us.",
    },
    { type: "h3", text: "Payments" },
    {
      type: "p",
      text: "We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).",
    },
    {
      type: "p",
      text: "We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.",
    },
    { type: "h2", text: "Use of Information for Business Purposes or Commercial Purposes" },
    {
      type: "p",
      text: 'We may use or disclose personal information We collect for "business purposes" or commercial purposes.',
    },
    { type: "h2", text: "Share of Personal & Business Information" },
    {
      type: "p",
      text: "We may share Your personal information identified in the above categories with the following categories of third parties:",
    },
    {
      type: "ul",
      items: [
        "Service Providers",
        "Payment processors",
        "Our affiliates",
        "Our business partners",
        "Third party vendors to whom You or Your agents authorize Us to disclose Your personal information in connection with products or services We provide to You.",
      ],
    },
    {
      type: "p",
      text: "You may exercise your rights to notice and opt out to restrain the Company from sharing the personal data with any third party or request for deletion of the personal data.",
    },
    { type: "h2", text: "Links to Other Websites" },
    {
      type: "p",
      text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
    },
    {
      type: "p",
      text: "We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.",
    },
    { type: "h2", text: "Changes to this Privacy Policy" },
    {
      type: "p",
      text: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
    },
    {
      type: "p",
      text: 'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.',
    },
    {
      type: "p",
      text: "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
    },
    { type: "h2", text: "Contact Us" },
    {
      type: "p",
      text: "If you have any questions about this Privacy Policy, you can contact us:",
    },
    {
      type: "ul",
      items: [
        `By visiting this page on our website: ${CONTACT_URL}`,
        `By sending us an email: ${SITE.email}`,
      ],
    },
  ];
}
